[project]
name = "tdd-example"
version = "0.1.0"
description = "TDD API REST example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "expects>=0.9.0",
    "fastapi[standard]>=0.118.0",
    "httpx>=0.28.1",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "ruff>=0.13.2",
]
